"""Render only the matched 3x3 expert/learned/Kazuki comparison.

Controller traces are generated by :mod:`sfm_b1_density_diagnostic`; this
module never reruns, selects, or alters a controller.  It is intentionally
separate from the query-gathering renderer so ID/OOD method comparisons do not
require unrelated expansion traces.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os

import torch

import sfm_b1_density_viz as V


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def render(method_runs_path, output_dir, *, scenario):
    bundle = torch.load(method_runs_path, map_location="cpu", weights_only=False)
    shared = bundle.get("shared_snapshot") if isinstance(bundle, dict) else None
    if not isinstance(shared, dict) or "step" not in shared:
        raise ValueError("method trace bundle requires driver-declared shared_snapshot.step")
    runs = V.normalize_method_bundle(bundle, scenario_id=int(scenario))
    os.makedirs(output_dir, exist_ok=False)
    png = os.path.join(output_dir, "method_gamma_3x3.png")
    mp4 = os.path.join(output_dir, "method_gamma_3x3.mp4")
    report_path = os.path.join(output_dir, "method_gamma_3x3.json")
    report = V.render_method_gamma_comparison(
        runs, png, snapshot_step=int(shared["step"]), output_mp4=mp4,
        report_path=report_path,
    )
    manifest = dict(
        status="SFM_B1_METHOD_VISUALIZATION_COMPLETE",
        controllers_rerun_by_renderer=False,
        source=dict(
            path=os.path.abspath(method_runs_path),
            sha256=_sha256(method_runs_path),
        ),
        scenario_id=int(scenario), shared_snapshot=shared,
        report=report,
        artifacts={
            os.path.basename(path): dict(
                path=os.path.abspath(path), bytes=os.path.getsize(path), sha256=_sha256(path),
            )
            for path in (png, mp4, report_path)
        },
    )
    with open(os.path.join(output_dir, "COMPLETE.json"), "w") as stream:
        json.dump(manifest, stream, indent=2)
    return manifest


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--method-runs", required=True)
    parser.add_argument("--scenario", required=True, type=int)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args(argv)
    render(args.method_runs, args.output_dir, scenario=args.scenario)


if __name__ == "__main__":
    main()
